language: c

compiler: gcc

script: make && make test

before_install:   
  - export SCRIPTS=./scripts/travis

install: 
  - chmod +x $SCRIPTS/travis_install.sh
  - sudo -E $SCRIPTS/travis_install.sh
